version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./chain:/root
    ports:
      - '${API_PORT}:${API_PORT}'
      - '5431:5431'
      - '9229:9229'
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo_data:/data/configdb
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
    name: webnet
volumes:
  mongo_data:
